In [ ]:
print("hello World")

In [ ]:
pip install numpy

In [1]:
import numpy as np
## create array Using numpy
## Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)
print(type(arr1))
print("Shape of 1D Array:", arr1.shape)

1D Array: [1 2 3 4 5]
<class 'numpy.ndarray'>
Shape of 1D Array: (5,)


In [ ]:
arr2= np.array([1, 2, 3,4,5])
arr2.reshape(1, 5) ## One Row and 5 colums
               

In [ ]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

In [2]:
## Array slicing and indexing
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print("2D Array:\n", arr)


2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [3]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [19]:
print(arr[1:0:-1])  # Slicing the array to get the second row in reverse order

[[ 6  7  8  9 10]]


In [22]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[ 3  4  5]
 [ 8  9 10]]


In [37]:
print(arr[0:3:2])

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [38]:
print(arr[0,1])

2


In [50]:
print(arr[:, 1:-1]) ## Acessing all the middle elements in the second column


[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [51]:
## Statistical Concept Normalization
data= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mean = np.mean(data, axis=0)  # Mean along the columns
std_dev = np.std(data, axis=0)  # Standard deviation along the columns
normalized_data = (data - mean) / std_dev  # Normalization

print("Original Data:\n", data)
print("Mean:\n", mean)
print("Standard Deviation:\n", std_dev)
print("Normalized Data:\n", normalized_data)
## Statistical Concept Standardization


Original Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean:
 [4. 5. 6.]
Standard Deviation:
 [2.44948974 2.44948974 2.44948974]
Normalized Data:
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [54]:
## Logical Operations
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
logical_condition = arr > 5  # Create a logical condition
print("Original Array:\n", arr)
print("Logical Condition (arr > 5):\n", logical_condition)


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Logical Condition (arr > 5):
 [[False False False]
 [False False  True]
 [ True  True  True]]
